State.create(id: 1, description: 'Acre', acronym: 'AC')
State.create(id: 2, description: 'Alagoas', acronym: 'AL')
State.create(id: 3, description: 'Amapá', acronym: 'AP')
State.create(id: 4, description: 'Amazonas', acronym: 'AM')
State.create(id: 5, description: 'Bahia', acronym: 'BA')
State.create(id: 6, description: 'Ceará', acronym: 'CE')
State.create(id: 7, description: 'Distrito Federal', acronym: 'DF')
State.create(id: 8, description: 'Espírito Santo', acronym: 'ES')
State.create(id: 9, description: 'Goiás', acronym: 'GO')
State.create(id: 10, description: 'Maranhão', acronym: 'MA')
State.create(id: 11, description: 'Mato Grosso', acronym: 'MT')
State.create(id: 12, description: 'Mato Grosso do Sul', acronym: 'MS')
State.create(id: 13, description: 'Minas Gerais', acronym: 'MG')
State.create(id: 14, description: 'Pará', acronym: 'PA')
State.create(id: 15, description: 'Paraíba', acronym: 'PB')
State.create(id: 16, description: 'Paraná', acronym: 'PR')
State.create(id: 17, description: 'Pernambuco', acronym: 'PE')
State.create(id: 18, description: 'Piauí', acronym: 'PI')
State.create(id: 19, description: 'Rio de Janeiro', acronym: 'RJ')
State.create(id: 20, description: 'Rio Grande do Norte', acronym: 'RN')
State.create(id: 21, description: 'Rio Grande do Sul', acronym: 'RS')
State.create(id: 22, description: 'Rondônia', acronym: 'RO')
State.create(id: 23, description: 'Roraima', acronym: 'RR')
State.create(id: 24, description: 'Santa Catarina', acronym: 'SC')
State.create(id: 25, description: 'São Paulo', acronym: 'SP')
State.create(id: 26, description: 'Sergipe', acronym: 'SE')
State.create(id: 27, description: 'Tocantins', acronym: 'TO')